In [3]:
import numpy as np

# Stochastic Matrices

These guys are matrices that predict a probability distribution iteratively. You present a "current" distribution, then you multiply by the "transition matrix" and it  tells you the "next" distribution.


In [4]:
#
# define a transition matrix
#
T = np.array([[0.1, 0.2, 0.3],
             [0.5,0.3,0.6],
             [0.4,0.5,0.1]])
T

array([[0.1, 0.2, 0.3],
       [0.5, 0.3, 0.6],
       [0.4, 0.5, 0.1]])

In [5]:
#
# Start out with a random prob distribution vector
#

x0 = np.array([np.random.rand(3)]).T
x0 = x0/x0.sum()
x0

array([[0.01285965],
       [0.31088394],
       [0.67625641]])

In [6]:
x1 = T.dot(x0)
x1

array([[0.26633968],
       [0.50544885],
       [0.22821147]])

In [7]:
x2 = T.dot(x1)
x2

array([[0.19618718],
       [0.42173138],
       [0.38208144]])

In [8]:
x3 = T.dot(x2)
x3

array([[0.21858943],
       [0.45386187],
       [0.3275487 ]])

In [9]:
xn = x3
for i in range(100):
    xn = T.dot(xn)
    
xn
    

array([[0.21290323],
       [0.44516129],
       [0.34193548]])

In [10]:
vals, vecs = np.linalg.eig(T)
vals

array([ 1.       , -0.1381966, -0.3618034])

In [48]:
vecs[:,0]/vecs[:,0].sum()

array([0.21290323, 0.44516129, 0.34193548])

In [12]:
vecs.sum(axis=0)

array([ 1.66570400e+00, -8.32667268e-16,  1.11022302e-16])

In [13]:
vecs/vecs.sum(axis=0)[0]

array([[ 0.21290323,  0.48569073, -0.18551735],
       [ 0.44516129, -0.30017338, -0.30017338],
       [ 0.34193548, -0.18551735,  0.48569073]])

In [16]:
x0 = np.array([[1/3,1/3,1/3]]).T
x0

array([[0.33333333],
       [0.33333333],
       [0.33333333]])

In [18]:
vecs[:,0]

array([0.35463375, 0.74150694, 0.5695633 ])

In [22]:
vecs[:,1]

array([ 0.80901699, -0.5       , -0.30901699])

In [20]:
vecs[:,2]

array([-0.30901699, -0.5       ,  0.80901699])

x0 = c0*vecs[:,0] + c1*vecs[:,1] + c2*vecs[:,2]

T*x0 = T*(c0*vecs[:,0] + c1*vecs[:,1] + c2*vecs[:,2])

     = c0*1*v0 + c1*(-0.138)*v1 + c2*(-0.3618)*v2
     

T*T*x0 = c0*1*1*v0 + c1*(-0.138)**2*v1 + c2*(-0.3618)**2*v2
T*T*T*x0 = c0*1**3*v0 + c1*((-0.138)**3*v1 + c2*(-0.3618)**3*v2
(T**100)x0 = c0*1**100*v0 + c1*((-0.138)**100*v1 + c2*(-0.3618)**100*v2

In [47]:
-0.3618**100

-7.028396476918598e-45

In [25]:
T.dot(vecs[:,0])

array([0.35463375, 0.74150694, 0.5695633 ])

In [38]:
T.dot(vecs[:,1]), vecs[:,1],

(array([-0.1118034,  0.0690983,  0.0427051]),
 array([ 0.80901699, -0.5       , -0.30901699]))

In [30]:
vecs[:,1]

array([ 0.80901699, -0.5       , -0.30901699])

In [33]:
-.1118/.8090, 0.0690983/ -0.5, 0.0427051/-0.30901699

(-0.13819530284301607, -0.1381966, -0.13819660854246235)

In [34]:
a = np.array([1,2,3])
b = np.array([2,4,6])

In [35]:
a/b

array([0.5, 0.5, 0.5])

In [40]:
T.dot(x0)/x0, x0

(array([[0.6],
        [1.4],
        [1. ]]),
 array([[0.33333333],
        [0.33333333],
        [0.33333333]]))